### ISSUE TITLE
glowing-bear-ssl-proxy should not rely on docker IP addresses

### ISSUE THREAD

**Issue by tgymnich** [thehyve/glowing-bear-docker#44]
glowing-bear-ssl-proxy should not rely on internal docker IP addresses since they might be different on some systems. Using dns names and docker networks is more flexible and reliable. I suggest using the docker networks defined in `docker-compose.yml` and `keycloak.yml`. This can also reduce the number of ports exposed to the outside and thus improve security.

External networks can be used like this:

```
networks:
  default:
    external:
      name: my-pre-existing-network
```
